spring:
  application:
    name: deal-service
  profiles:
    active: default

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: public
    drop-first: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

calculator:
  service:
    url: http://localhost:8080
  endpoints:
    base: /api/v1/calculator
    offers: /offers
    calc: /calc

kafka:
  topics:
    finish-registration: finish-registration
    create-documents: create-documents
    send-documents: send-documents
    send-ses: send-ses
    credit-issued: credit-issued
    statement-denied: statement-denied