spring:
  application:
    name: deal-service
  profiles:
    active: default

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

calculator:
  service:
    url: http://localhost:8080