server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: public
    drop-first: false

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    path: /api-docs
  servers:
    - url: /api/v1/deal
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    org.neoflex.deal: DEBUG
    org.neoflex.statement.interceptor: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
    org.hibernate.engine.jdbc: WARN

calculator:
  service:
    url: ${CALCULATOR_SERVICE_URL:http://calculator:8080}
  endpoints:
    base: "${CALCULATOR_ENDPOINTS_BASE:/api/v1/calculator}"
    offers: "${CALCULATOR_ENDPOINTS_OFFERS:/offers}"
    calc: "${CALCULATOR_ENDPOINTS_CALC:/calc}"

gateway:
  service:
    url: ${GATEWAY_URL:http://localhost:8084}

kafka:
  topics:
    finish-registration: finish-registration
    create-documents: create-documents
    send-documents: send-documents
    send-ses: send-ses
    credit-issued: credit-issued
    statement-denied: statement-denied