server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  servers:
    - url: /api/v1/statement
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    org.neoflex.statement: DEBUG
    org.neoflex.statement.interceptor: DEBUG
    org.springframework.web: INFO
    org.springframework.web.servlet: INFO

client:
  deal:
    address: ${DEAL_SERVICE_ADDRESS:http://localhost:8081}
    url: ${CLIENT_DEAL_URL:/api/v1/deal}
    api:
      calculate:
        path: ${CLIENT_DEAL_API_CALCULATE_PATH:/statement}
      select:
        path: ${CLIENT_DEAL_API_SELECT_PATH:/offer/select}

gateway:
  service:
    url: ${GATEWAY_URL:http://localhost:8084}

credit:
  support:
    logging:
      enabled: true