server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: statement-api
          uri: http://statement:8082
          predicates:
            - Path=/api/v1/statement/**

        - id: statement-docs
          uri: http://statement:8082
          predicates:
            - Path=/statement/**
          filters:
            - RewritePath=/statement/(?<path>.*), /$\{path}

        - id: deal-api
          uri: http://deal:8081
          predicates:
            - Path=/api/v1/deal/**

        - id: deal-docs
          uri: http://deal:8081
          predicates:
            - Path=/deal/**
          filters:
            - RewritePath=/deal/(?<path>.*), /$\{path}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Deal Service
        url: ${DEAL_SERVICE_URL:http://localhost:8081/api-docs}
      - name: Statement Service
        url: ${STATEMENT_SERVICE_URL:http://localhost:8082/api-docs}