server.port=8080

springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.url=/v3/api-docs

logging.level.org.springdoc=DEBUG

loan.calculator.base-rate=15.0
loan.calculator.insurance-cost-percent=2.0
loan.calculator.insurance-rate-discount=3.0
loan.calculator.salary-client-discount=1.0

loan.calculator.self-emploe-rate-add=2.0
loan.calculator.busines-owner-rate-add=1.0

loan.calculator.mid-manager-rate-discount=2.0
loan.calculator.top-manager-rate-discount=3.0

loan.calculator.married-rate-discount=3.0
loan.calculator.divorced-rate-add=1.0

loan.calculator.male-rate-discount=3.0
loan.calculator.female-rate-discount=3.0
loan.calculator.not-binary-rate-add=7.0