server.port=8080

springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.url=/v3/api-docs

logging.level.org.springdoc=DEBUG

loan.calculator.base-rate=15.0
loan.calculator.insurance-cost-percent=2.0
loan.calculator.insurance-rate-discount=3.0